name: budgetfrontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dotted_border: ^2.0.0
  card_swiper: ^2.0.4
  percent_indicator: ^4.2.3
  http: ^1.3.0
  simple_animations: ^3.0.0 
  supercharged: ^2.1.0
  get: ^4.3.8
  shared_preferences: ^2.5.3
  fl_chart: ^0.71.0
  persistent_bottom_nav_bar_v2: ^5.3.1
  get_storage: ^2.1.1
  flutter_colorpicker: ^1.1.0
  flutter_iconpicker: ^3.3.3
  flutter_date_pickers: ^0.4.3
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/app_logo1.png"
  image_path_ios: "assets/icon/app_logo1.png"
  adaptive_icon_foreground: "assets/icon/app_logo1.png"
  adaptive_icon_background: "#1D1D1D"
  # Spotify-style dark background

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/
    - assets/background/

  # Example for fonts (if needed)
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont.ttf
